cloudscape-design/component-toolkit

package.json, src/internal/base-component/__tests__/use-component-metadata.test.tsx, src/internal/base-component/__tests__/use-component-metrics.test.tsx, src/internal/base-component/component-metadata.ts, src/internal/base-component/component-metrics.ts, src/internal/base-component/index.ts, src/internal/base-component/init-awsui-versions.ts, src/internal/base-component/metrics/formatters.ts, src/internal/base-component/metrics/log-clients.ts, src/internal/base-component/metrics/metrics.ts
Based on: https://github.com/cloudscape-design/components/pull/705.
Required for: https://github.com/cloudscape-design/components/pull/714.
=> chore: Add internal base-component utils

package-lock.json, package.json
=> chore: Remove react-dom from peer deps

package-lock.json, package.json
Reason: downstream build issues
=> chore: Remove peer deps from package.json

package-lock.json
=> chore: Update package-lock

src/container-queries/use-resize-observer.ts, src/internal/singleton-handler/__tests__/create-singleton-handler.test.tsx, src/internal/singleton-handler/__tests__/create-singleton-state.test.tsx, src/internal/singleton-handler/index.ts, src/internal/stable-callback/__tests__/use-stable-event-handler.test.tsx, src/internal/stable-callback/index.ts, src/internal/visual-mode/__tests__/use-visual-mode.test.tsx, src/internal/visual-mode/__tests__/utils.ts, src/internal/visual-mode/index.ts, src/use-controllable-state/use-controllable-state.ts
Add more internal tools to share between components and board-components.
=> chore: Add internal tools for visual mode

src/dom/__tests__/node-contains.test.ts, src/dom/node-contains.ts
Porting changes from https://github.com/cloudscape-design/components/pull/1374
* Added support for `EventTarget` arguments to allow `nodeContains(element, event.target)` without type issues
* Removed fallback, because in our supported browsers the native code works
* Updated tests
Note, the utility is still not used inside our components. I will open a follow up PR with migration
=> feat: Upgrade nodeContains utility

src/internal/base-component/metrics/metrics.ts, src/internal/logging.ts
Use more optimal storage in case if there will be too many metrics or messages to remember
=> chore: Use sets for caching already used values

src/internal/base-component/__tests__/metrics.test.ts, src/internal/base-component/__tests__/use-component-metrics.test.tsx, src/internal/base-component/component-metrics.ts, src/internal/base-component/metrics/formatters.ts, src/internal/base-component/metrics/interfaces.ts, src/internal/base-component/metrics/log-clients.ts, src/internal/base-component/metrics/metrics.ts
Implement this feature: Vg2OAA5ArJn8
Code example:
```js
useComponentMetrics('test-component', source, {
// new – report props here
props: { variant },
});
```
=> feat: Support component properties reporting

src/internal/base-component/metrics/log-clients.ts
These types are not used outside this module, but when it happens, it may fail type check on consumers' end.
=> chore: Do not export window-based types

package.json
Explicitly include files list in package json
=> chore: Include files list in package json

tsconfig.json
Sync typescript target config in this repository with the config in the main repo.
* PR build
* Did a dry-run with my feature branch: 6798034791
---
=> fix: upgrade typescript es target

package.json, scripts/in-github-workflow.js
Unify this package with others in our project
=> chore: remove preinstall script

src/internal/base-component/__tests__/metrics.test.ts, src/internal/base-component/metrics/interfaces.ts
=> chore: Add component metrics metadata property

src/internal/index.ts, src/internal/logging.ts, src/internal/visual-mode/__tests__/use-runtime-visual-refresh.test.tsx, src/use-controllable-state/__tests__/use-controllable.test.tsx
Make it possible to test warnOnce cases multiple times
=> chore: allow resetting warnOnce messages

package.json
Added an extra internal in the previous PR and only read the comment after merging.
=> chore: Remove extra internal

src/internal/base-component/__tests__/metrics.test.ts, src/internal/base-component/metrics/interfaces.ts
=> chore: Support null values in property metrics

src/internal/direction/__tests__/direction.test.tsx, src/internal/direction/index.ts, src/internal/index.ts
This PR migrates the direction utilities from the components package to the component toolkit so they can be shared across packages.
=> chore: Add direction utilities to component toolkit.

package-lock.json, package.json, src/internal/focus-visible/__integ__/focus-visible.test.ts, src/internal/focus-visible/__tests__/index.test.tsx, src/internal/focus-visible/index.scss, src/internal/focus-visible/index.ts, src/internal/index.ts, src/internal/keycode.ts, test-pages/src/pages/focus-visible.module.scss, test-pages/src/pages/focus-visible.page.tsx
*Description of changes:* Move `focus-visible` from https://github.com/cloudscape-design/components/tree/main/src/internal/hooks/focus-visible
Will follow up by removing it from there and https://github.com/cloudscape-design/chat-components/blob/main/src/internal/utils/focus-visible.ts
=> chore: Add internal/focus-visible

package.json, src/internal/analytics-metadata/__tests__/utils.test.tsx, src/internal/analytics-metadata/index.ts, src/internal/analytics-metadata/utils.ts, src/internal/index.ts
=> chore: Separate exports to avoid bundling analytics metadata utilities

src/internal/analytics-metadata/__tests__/attributes.test.tsx, src/internal/analytics-metadata/__tests__/dom-utils.test.tsx, src/internal/analytics-metadata/__tests__/labels-utils.test.tsx, src/internal/analytics-metadata/__tests__/testing-utils.test.tsx, src/internal/analytics-metadata/__tests__/utils.test.tsx, src/internal/analytics-metadata/attributes.ts, src/internal/analytics-metadata/index.ts, src/internal/global-flags/index.ts
Introduction of a global flag to activate analytics metadata
=> feat: Introduce activation mechanism for analytics metadata

package.json
=> fix: Export path for internal testing utilities

src/internal/analytics-metadata/__tests__/components.tsx, src/internal/analytics-metadata/__tests__/labels-utils.test.tsx, src/internal/analytics-metadata/__tests__/testing-utils.test.tsx, src/internal/analytics-metadata/__tests__/utils.test.tsx, src/internal/analytics-metadata/interfaces.ts, src/internal/analytics-metadata/testing-utils.ts
To address https://github.com/cloudscape-design/components/pull/2502#discussion_r1688075864
=> feat: Allow label selector to be undefined

src/internal/analytics-metadata/index.ts
Needed for https://github.com/cloudscape-design/components/pull/2519#discussion_r1691507903
=> chore: Export label identifier from analytics metadata

.github/workflows/release-gh-notes.yml
Add missing workflow to generate release notes for this package
=> Add release workflow

src/dom/__tests__/element-types.test.ts, src/dom/element-types.ts, src/dom/find-up-until.ts, src/dom/node-contains.ts
A follow-up fix for https://github.com/cloudscape-design/components/pull/2749
=> fix: Make dom findUpUntil util work within iframes

package-lock.json, package.json
Upgrade dependency. No breaking changes for our use-case: https://vite.dev/guide/migration.html#migration-from-v5
=> chore: Upgrade vite
