- package-lock.json
- package.json
`tslib` is included in the final bundled output, therefore it needs to be a peer dependency in addition to a development dependency.
(This change is also applicable to the AWS UI component toolkit, which is not present on GitHub for a PR.)
> fix: add `tslib` to `dependencies`

- src/internal/logging.ts
- src/use-controllable-state/__tests__/use-controllable.test.tsx
The `warnOnce` function requires the same format as in components repository so that the function and dependant functions can be consumed from the toolkit. 
> chore: Align warnOnce format with components/internal/logging

- src/internal/visual-mode/__tests__/motion.test.tsx
- src/internal/visual-mode/__tests__/use-visual-mode.test.tsx
When updating components to use visual-mode utils from the toolkit I found out there were tests created for isMotionDisabled. Using this tests instead of ones introduced previously.
> refactor: Add original isMotionDisabled tests from components

- src/internal/base-component/__tests__/use-component-metadata.test.tsx
- src/internal/base-component/component-metadata.ts
*Issue #, if available:* n/a
This PR extends our `useComponentMetadata` hook with an option to provide additional component-specific metadata. We plan to use this option to expose e.g. whether a button is a primary or default variant, what the placeholder text of a Select is, and so on. See also document FZakAmaNW5fQ .
Example usage in the Button component:
```js
const baseComponentProps = useBaseComponent('Button', { variant, disabled, loading });
```
---
> feat: Support `componentConfiguration` in the component metadata property

- src/internal/base-component/component-metadata.ts
*Issue #, if available:* n/a
*Description of changes:*  
The metadata that is attached to each component's DOM node will now be updated on every render. This ensures that changes to the component properties are properly reflected.
> fix: Keep metadata synchronised with updated component configuration

- src/internal/index.ts
- src/internal/visual-mode/__tests__/use-runtime-visual-refresh.test.tsx
- src/internal/visual-mode/index.ts
Move [`useVisualRefreshDynamic` in Component ](https://github.com/cloudscape-design/components/blob/main/src/internal/hooks/use-visual-mode/index.ts#L17) into toolkit, reduce duplications in Components and [Dashboard](https://github.com/cloudscape-design/components/blob/main/src/internal/hooks/use-visual-mode/index.ts#L17)
> chore: Add useVisualRefresh hook to internal

- .github/workflows/build-lint-test.yml
- .github/workflows/dry-run.yml
- .github/workflows/release.yml
This PR switches to the new shared repository for GitHub workflows and actions: https://github.com/cloudscape-design/actions.
For the most recent changes to the shared workflows, see https://github.com/cloudscape-design/actions/pull/1. The new configuration was successfully tested in this Draft PR: https://github.com/cloudscape-design/components/pull/1672.
> chore: Switch to new actions repo for workflows

- src/dom/node-contains.ts
this might crazy but we have a very rare edge case when the parent and descendant elements are created in a window instance and then rendered in an iframe making `descendant instanceof Node` false since `descendant` has a different `window.Node` 
This PR uses `nodeType` instead
> fix: check for descendant nodeType in nodeContains function

- src/internal/base-component/__tests__/metrics-init.ts
- src/internal/base-component/__tests__/metrics.test.ts
- src/internal/base-component/__tests__/panorama-metrics.test.ts
- src/internal/base-component/__tests__/use-component-metrics.test.tsx
- src/internal/base-component/metrics/log-clients.ts
Bring these values up to date with the receiver's end.
~"Dry-run / dry-run / Components unit tests" is expected to fail. They will pass after merging https://github.com/cloudscape-design/components/pull/1919~ All passes now
> chore: Update metric length limits

- src/internal/base-component/__tests__/use-component-metadata.test.tsx
- src/internal/base-component/component-metadata.ts
This is a private API and it is unused after https://github.com/cloudscape-design/components/pull/1928
> remove extended component metadata reporting

- src/internal/base-component/__tests__/panorama-metrics.test.ts
- src/internal/base-component/metrics/log-clients.ts
n/a
This change allows to provide a timestamp for a metric event.
> feat: Support custom timestamps in metrics

- src/internal/base-component/__tests__/use-component-metadata.test.tsx
- src/internal/base-component/component-metadata.ts
- src/internal/base-component/metrics/interfaces.ts
Extends the useComponentMetadata hook to accept an optional field for analytics metadata. This metadata will get stored on the node alongside the component metadata.
Design doc: DM
> chore: Add analytics metadata property to component nodes

- src/internal/index.ts
Type-only exports are only supported in Typescript 3.8 or higher. The type-only export prevents consumers of the package to use it in an environment that is using an older Typescript version.
This replaces the type-only export with a full export. This should not make any difference in the generated JS output of the internal folder's index file.
> chore: Replace type-only export with full export

- package.json
Ensure that styles as well as JS are included in build output for focus-visible.
TBC: if we end up with many more similar helpers that include CSS in the future then we might want to do this in a more automated way, but for now it seems a relatively rare occurrence.
> chore: Include focus-visible styles in build output

- src/internal/analytics-metadata/__tests__/attributes.test.tsx
- src/internal/analytics-metadata/__tests__/components.tsx
- src/internal/analytics-metadata/__tests__/dom-utils.test.tsx
- src/internal/analytics-metadata/__tests__/index.test.tsx
- src/internal/analytics-metadata/__tests__/labels-utils.test.tsx
- src/internal/analytics-metadata/__tests__/metadata-utils.test.ts
- src/internal/analytics-metadata/attributes.ts
- src/internal/analytics-metadata/dom-utils.ts
- src/internal/analytics-metadata/index.ts
- src/internal/analytics-metadata/interfaces.ts
- src/internal/analytics-metadata/labels-utils.ts
- src/internal/analytics-metadata/metadata-utils.ts
- src/internal/index.ts
Partial implementation of internal utilities for enhanced analytics metadata injection and collection.
> feat: Utilities for generated analytics metadata

- src/internal/focus-visible/index.scss
This allows `focus-visible` to be used in places where we manually override focus (e.g. because a different element is focused than the one we want to actually show the focus ring around: https://github.com/cloudscape-design/components/blob/main/src/file-upload/file-input/styles.scss#L25)
> chore: Add additional focus-visible mixin to support "fake" focus

- src/internal/analytics-metadata/__tests__/test-utils.test.tsx
- src/internal/analytics-metadata/index.ts
- src/internal/analytics-metadata/test-utils.ts
- src/internal/index.ts
Additional method to allow for testing of the analytics metadata. For example, it will allow to test that component names have a certain prefix, and that class names used for labels are part of a certain set.
> feat: Add method for testing purposes

- src/internal/global-flags/__tests__/global-flags-ssr.test.ts
- src/internal/global-flags/__tests__/global-flags.test.ts
- src/internal/global-flags/index.ts
- src/internal/index.ts
To be able to use it to enable/disable analytics metadata decoration. Copied from https://github.com/cloudscape-design/components/blob/main/src/internal/utils/global-flags.ts
> chore: Move global flags management from component to toolkit

- src/internal/global-flags/__tests__/global-flags-ssr.test.ts
- src/internal/global-flags/index.ts
- src/internal/visual-mode/__tests__/use-runtime-visual-refresh.ssr.test.tsx
- src/internal/visual-mode/index.ts
Support feature flags in SSR
```js
globalThis[Symbol.for('awsui-visual-refresh-flag')] = () => true
```
It was already working for other feature flags, but not for the main VR flag
> feat: Support configuring VR feature flag in SSR environment

- src/internal/global-flags/__tests__/global-flags-ssr.test.ts
- src/internal/global-flags/__tests__/global-flags.test.ts
- src/internal/global-flags/index.ts
- src/internal/index.ts
Needed for testing purposes (e.g. https://github.com/cloudscape-design/components/blob/main/src/internal/widgets/__tests__/utils.ts)
> feat: Add global flags setter for testing purposes

- package.json
- src/internal/base-component/metrics/metrics.ts
- src/internal/index.ts
- src/internal/testing.ts
Allow for more clear separation what is imported in prod code and what is for testing.
After migration, I will clean up current main exports from test helpers
> chore: Expose testing helpers as separate export

- src/internal/analytics-metadata/__tests__/labels-utils.test.tsx
- src/internal/analytics-metadata/labels-utils.ts
To remove noise introduces, for example, by external icon in links
> chore: trim analytics labels

- src/internal/global-flags/index.ts
Add a new feature flag, `appLayoutToolbar` to allow enabling the App Layout Toolbar design, but without the widget (like the existing `appLayoutWidget` works)
> chore: Add global flag for app layout toolbar

- .github/workflows/build-lint-test.yml
- .github/workflows/dry-run.yml
- .github/workflows/lint-pr.yml
to enable merge queue feature in the repo, trigger workflows that are checked in PR when merge queue is requested.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
tested in global-styles repo: https://github.com/cloudscape-design/global-styles/pull/48
I also noted the lint-pr workflow is not used here, so I also added it.
> chore: Add lint-pr workflow and trigger required workflows on merge_group event

- package.json
*Issue #, if available:* AWSUI-51276
*Description of changes:* Some preparatory work for upgrading webdriverio: support ESM in jest as-per https://jestjs.io/docs/ecmascript-modules
> chore: Add support for ESM in jest

- src/internal/container-queries/__integ__/use-resize-observer.test.ts
Replacing browser.setWindowSize (WebdriverIO) with page.setWindowSize (browser-test-tools) to take advantage of the new Chrome headless mode fix (see https://github.com/cloudscape-design/browser-test-tools/pull/105).
> chore: Use setWindowSize browser-test-tools util

- src/internal/analytics-metadata/__tests__/labels-utils.test.tsx
- src/internal/analytics-metadata/interfaces.ts
- src/internal/analytics-metadata/labels-utils.ts
Needed to identify group labels in dropdown-based components when expandToViewport=true
> feat: Allow body selector for labels roots in analytics metadata

- src/internal/container-queries/__integ__/use-resize-observer.test.ts
- test-pages/src/pages/use-resize-observer-test.tsx
The window inner width/height might change due to changes in Chromium headless mode. Updating an integration test to no longer depend on the exact screen size.
See https://github.com/cloudscape-design/browser-test-tools/pull/105
> refactor: Resize observer test to not depend on exact window size

- src/internal/visual-mode/__tests__/motion.test.tsx
- src/internal/visual-mode/index.ts
In some rare cases, `window.mediaMatch` returns null, to support the usage of iframes this PR replaces `window` with `element.ownerDocument.defaultView`
> chore: Use ownerDocument.defaultView for isMotionDisabled

- src/internal/visual-mode/index.ts
When using test utils in some of our components we get react act warnings, an example of a utility that does that is inside the Autosuggest wrapper `wrapper.findAutosuggest().openDrawer()`.
This happens in all of the components that changes a state like opening a drawer, closing a drawer, or doing an action that will create a transitition effect. The logs of that act warnings:
```
console.error                                                                                          
Warning: An update to Transition inside a test was not wrapped in act(...).                          
When testing, code that causes React state updates should be wrapped into act(...):                  
act(() => {                                                                                          
/* …
```
> fix: FIx react act warnings

- src/internal/visual-mode/index.ts
follows up a fix in this PR: https://github.com/cloudscape-design/component-toolkit/commit/2b188cf55e96fd01060f28916005c386ad09008c
it turns out that all usages that uses the `useMutationObserver` requires this fix.
> chore: Apply act warning fix to all hooks that uses useMutationObserver

- src/internal/analytics-metadata/__tests__/metadata-utils.test.ts
- src/internal/analytics-metadata/metadata-utils.ts
*Issue #, if available:* AWSUI-59898
Currently, if a property in source object contains an empty string, merging logic incorrectly changes it to an empty object. 
That happens, for example, in a table without header. I'll add a test to components package for this specific use-case
> fix: Correctly merge empty strings in analytics metadata

- package.json
- src/internal/index.ts
- src/internal/metrics.ts
Reduce loaded size when importing metrics
```js
import { Metrics } from '@cloudscape-design/component-toolkit/internal'; // 3.8 Kb
import { Metrics } from '@cloudscape-design/component-toolkit/internal/metrics'; // 0.7 Kb
```
Why is this happening – `@cloudscape-design/component-toolkit/internal` also loads ResizeObserver polyfill which is a side effect, but side effects do not tree shake
> chore: Expose metrics as separate file export

- src/internal/container-queries/use-resize-observer.ts
Optimization for React, if there will be multiple state changes inside `onObserve`, they will be batched into a single re-render
> fix: Apply batched updates to resize observer callback

- package.json
By default, bundlers are conservative and consider `Symbol.for(...)` call as a side effect and leave it in the bundle even if unused:
https://github.com/cloudscape-design/component-toolkit/blob/d5f68a152bf6f5f4226bc983d2c7d341600f5e0e/src/internal/global-flags/index.ts#L4C39-L4C78
Let's help them with a declaration
> chore: Mark package as side effects free

- src/internal/base-component/__tests__/metrics.test.ts
- src/internal/base-component/metrics/log-clients.ts
Before: try finding `AWSC.Clog.log` API first, then `panorama`
After: try `panorama` API first, then `AWSC.Clog.log`.
Part of the plan to eventually remove `AWSC.Clog.log` from our code after confirming the `panorama` API collects all data
> chore: Try sending metrics to panorama before clog API

- src/internal/base-component/__tests__/panorama-metrics.test.ts
- src/internal/base-component/metrics/log-clients.ts
Currently, if there are issues with metrics, we simply drop it. With this change, we will report an error message instead, which we can investigate
> feat: Report metric errors

- src/dom/__tests__/node-belongs.test.ts
- src/dom/index.ts
- src/dom/node-belongs.ts
- src/internal/index.ts
- src/internal/single-tab-stop/index.tsx
- src/internal/utils/circle-index.ts
In order to be able to import the newly created functions from component-toolkit, they need to be added to the index files.
> chore: Adds exports to index files

- src/internal/visual-mode/__tests__/use-runtime-visual-refresh.test.tsx
- src/internal/visual-mode/index.ts
This utility should live the pristine state
> fix: Make sure clearVisualRefreshState helper removes the class too

- src/internal/index.ts
- src/internal/portal/__tests__/portal.test.tsx
- src/internal/portal/index.tsx
Moves portal from https://github.com/cloudscape-design/components/tree/main/src/internal/components/portal to toolkit, to be reused in chart components.
> chore: Internal portal util

- src/internal/base-component/__tests__/use-component-metadata.test.tsx
- src/internal/base-component/component-metadata.ts
Allow easier debugging which theme is currently used in an app, by inspecting `element.__awsuiMetadata__.theme` property
> chore: Add additional metadata to reporting

- src/internal/base-component/metrics/interfaces.ts
The current analytics metadata gets added to the DOM element but only supports primitives. When introducing errorContext we will be using an object and so expanding support for it here.
> chore: Expand AnalyticsMetadata to allow JSON objects

- src/internal/index.ts
- src/internal/use-merge-refs/__tests__/use-merge-refs.test.tsx
- src/internal/use-merge-refs/index.tsx
Adds useMergeRefs util to be reused between components, board-components, chat-components, and chart-components.
> chore: Adds internal use-merge-refs util

- src/internal/index.ts
- src/internal/use-unique-id/__tests__/use-unique-id.test.tsx
- src/internal/use-unique-id/index.ts
Moving useRandomId and useUniqueId utils from components to toolkit to reuse for charts.
Rel: https://github.com/cloudscape-design/chart-components/pull/30
> chore: Internal unique ID utilities

- src/internal/analytics-metadata/__tests__/components.tsx
- src/internal/analytics-metadata/__tests__/page-scanner-utils.test.tsx
- src/internal/analytics-metadata/interfaces.ts
- src/internal/analytics-metadata/page-scanner-utils.ts
- src/internal/analytics-metadata/utils.ts
Initial implementation, missing support for iframes and portals.
> feat: Implement initial components tree utility

- src/internal/base-component/__tests__/panorama-metrics.test.ts
- src/internal/base-component/metrics/log-clients.ts
Porting logic from CR-188913901
> chore: Add support for panorama in isolated widgets

- src/internal/analytics-metadata/__tests__/dom-utils.test.tsx
- src/internal/analytics-metadata/__tests__/page-scanner-utils.test.tsx
- src/internal/analytics-metadata/attributes.ts
- src/internal/analytics-metadata/dom-utils.ts
- src/internal/analytics-metadata/labels-utils.ts
- src/internal/analytics-metadata/page-scanner-utils.ts
> feat: Add support for portals in page scanner utility

- src/internal/focus-visible/__tests__/iframes.test.tsx
- src/internal/focus-visible/__tests__/index.test.tsx
- src/internal/focus-visible/index.ts
*Issue #, if available:* AWSUI-60845
*Description of changes:* Supporting the niche but real use case where components are rendered into a same-origin iframe (typically using a React portal). We keep the reference counting logic, but extend it so that each frame (including the main one) has its own count. This should release first - the matching PR for the components package will follow.
Check my dev pipeline (AwsUi-v3-dwaraa) to see what it looks like.
This is a stopgap to resolve this issue so that the CSS focus-visible migration isn't tied to this simple bugfix. The "default keyboard" approach of the browser behavior compared to the "default mouse" approach of the JS implementation means that there are some async or initial page load scenarios where the focus ring appears where it …
> chore: Globally handle focus-visible management for application spanning multiple iframes

- src/internal/singleton-handler/__tests__/create-singleton-state.test.tsx
- src/internal/singleton-handler/index.ts
> _There are only two hard things in Computer Science: cache invalidation and naming things._
In this PR we got incorrect caching.
This affects our `useMobile` hook. Example:
```js
test('first', () => {
globalThis[forceMobileModeSymbol] = false;
render(<AppLayout />); // I see desktop view
// resize to mobile
act(() => {
globalThis[forceMobileModeSymbol] = true;
window.dispatchEvent(new CustomEvent('resize'));
});
// clean up flag to its original state
globalThis[forceMobileModeSymbol] = undefined;
});
test('second', () => {
// no overrides in this test, it should be desktop by default, but the mobile size is leaked from the previous test
render(<AppLayout />);
});
```
With the fix the "second" test will work as expected
By submitting …
> fix: Avoid stale state in singleton-handler

- src/internal/index.ts
- src/internal/single-tab-stop/__tests__/context.test.tsx
- src/internal/single-tab-stop/__tests__/utils.tsx
- src/internal/single-tab-stop/index.tsx
- src/internal/testing.ts
A follow-up for https://github.com/cloudscape-design/component-toolkit/pull/155.
We need more exports to replace the STSN utils from components with the toolkit version:
1. The renderWithSingleTabStopNavigation util used in multiple subscribed components tests
2. The SingleTabStopNavigationContext and defaultValue used for modal context reset. Instead of exposing these two I created a dedicated SingleTabStopNavigationReset component.
> chore: More internal stsn exports

- src/internal/single-tab-stop/__tests__/context.test.tsx
- src/internal/single-tab-stop/test-helpers/index.tsx
- src/internal/testing.ts
The currently exported `renderWithSingleTabStopNavigation` util requires a dependency on the react testing library. To avoid having this dependency, we export `TestSingleTabStopNavigationProvider` and `setTestSingleTabStopNavigationTarget` helpers instead. Once components code is migrated, the `renderWithSingleTabStopNavigation` export will be removed.
> chore: Export TestSingleTabStopNavigationProvider to avoid a dependency on RTL

- src/internal/single-tab-stop/__tests__/context.test.tsx
- src/internal/single-tab-stop/test-helpers/index.tsx
- src/internal/testing.ts
Removing deprecated test helper to avoid a dependency on React Testing Library.
Rel: AWSUI-61217
> chore: Removes deprecated stsn test helper

- src/internal/base-component/__tests__/metrics.test.ts
- src/internal/base-component/__tests__/use-component-metrics.test.tsx
- src/internal/base-component/metrics/formatters.ts
- src/internal/base-component/metrics/interfaces.ts
- src/internal/base-component/metrics/metrics.ts
*Description of changes:* Pass package name along with component metrics so that we can distinguish from components from different packages that have the same name (motivation: Pie Chart from Components vs Pie Chart from Chart Components).
> feat: Pass package source name in component usage metric

- package-lock.json
Addresses https://github.com/cloudscape-design/component-toolkit/security/dependabot/56 by updating tar-fs to 3.1.1 and ran `npm audit fix`
> chore: Update tar-fs version
